CREATE TABLE IF NOT EXISTS `Warehouse` (
  `Id` BIGINT(20) NOT NULL COMMENT '',
  `warehouseId` BIGINT(20) NOT NULL COMMENT '',
  `name` VARCHAR(255) NULL COMMENT '',
  `zipCode` INT(6) NULL COMMENT '',
  `city` VARCHAR(255) NULL COMMENT '',
  `address` VARCHAR(255) NULL COMMENT '',
  `addressNumber` int(6) NULL COMMENT '',
  `managerId` BIGINT(20) NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
